spring.application.name=user-management-api

spring.datasource.url=jdbc:mysql://localhost:3306/user_management
spring.datasource.username=root
spring.datasource.password=abhishek8103

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

server.port=8080

jwt.secret=MySuperSecretKeyForUserManagementApplication2026
jwt.expiration=86400000

file.upload-dir=uploads/profile